---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /home/rocky/AQUA-CARE-2025-June/task-1/step2/pvc-master/  # change here
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-quickstart-data-0
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/rocky/AQUA-CARE-2025-June/task-1/step2/pvc-data/  # change here
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - augnode1-5361855-iaas.novalocal # change here

