---
- name: Install k3s and configure kubeconfig
  hosts: all
  become: yes
  tasks:
    - name: Install k3s using official script
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure .k3s directory exists in home
      become: false
      file:
        path: "/home/ubuntu/.k3s"
        state: directory
        mode: '0755'

    - name: Copy k3s.yaml to user's .k3s directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "/home/ubuntu/.k3s/k3s.yaml"
        remote_src: yes
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'

    - name: Set KUBECONFIG environment variable in .bashrc
      lineinfile:
        path: "/home/ubuntu/.bashrc"
        line: 'export KUBECONFIG=$HOME/.k3s/k3s.yaml'
        state: present
      become: no

    - name: Display all pods in all namespaces
      shell: kubectl get pod -A
      environment:
        KUBECONFIG: "/home/ubuntu/.k3s/k3s.yaml"
      register: pods_output
      changed_when: false
