# =========================
# PVs for masters
# =========================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-0
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["augnode1-5361855-iaas.novalocal"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-master-node-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-1
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["vm2"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-master-node-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-master-2
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["vm3"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-master-node-2
---
# =========================
# PVs for data nodes
# =========================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-quickstart-data-0
spec:
  capacity:
    storage: 1000Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["augnode1-5361855-iaas.novalocal"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-data-nodes-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-quickstart-data-1
spec:
  capacity:
    storage: 1000Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["vm2"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-data-nodes-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-quickstart-data-2
spec:
  capacity:
    storage: 1000Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /tmp/pv-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["vm3"]
  claimRef:
    namespace: default
    name: elasticsearch-data-quickstart-es-data-nodes-2

